### ISSUE TITLE
download link to non .bag file

### ISSUE THREAD

**Issue by TankPi** [ternaris/marv#11]
I want to create a downloadable link to a non bag file. Any suggestion on how to do this? Thanks!

Sheers,

Frank

**Comment by NikolausDemmel** [comment]
You should be able to make that work using the `rellink` formatter in a table.

See for example: https://github.com/ternaris/marv-robotics/blob/9b454d94e8a4b85c8248801761c114baef4f47d7/marv_robotics/marv_profile/marv.conf.in#L135

Here you can see the format that `rellink` expects:

https://github.com/ternaris/marv/blob/b4b30fcb178fa4dffe4c41b408e7e7f353b23636/marv/helpers.py#L32-L37

I think (but I am not sure) you should be able to download other files in the scanroot as well through the "download" route.

Otherwise, there should also be the `link` formatter, which expects an absolute URI AFAIK.

**Comment by chaoflow** [comment]
@TankPi if the file is part of a dataset the [meta_table](https://github.com/ternaris/marv/blob/35c2a72586a755f67b3b223b962845ec63d8b9e8/marv_nodes/__init__.py#L84) widget will render a download link for it.

marv.conf:
```ini
nodes =
    marv_nodes:dataset
    marv_nodes:meta_table
detail_summary_widgets =
    summary_keyval
    meta_table
```

To create datasets that consist of files other than bags, you implement a customer scanner, see:
- https://ternaris.com/marv-robotics/docs/config.html#scanner
- https://ternaris.com/marv-robotics/docs/api/marv.html#module-marv.scanner
- https://ternaris.com/marv-robotics/docs/scan.html#marv_robotics.bag.scan

To link to external files, use the [link formatter](https://ternaris.com/marv-robotics/docs/config.html#link).
