### ISSUE TITLE
Open Source?

### ISSUE THREAD

**Issue by stsundermann** [ternaris/marv#30]
Why is there no source code for the javascript files? The whole front end is in the obfuscated main-built.js. It's almost impossible to change anything or add new features at all. Why is this project open source on Github if the main idea behind open source is contributing to software. Pushing obfuscated code as open source is a really strange idea and does not make any sense because it makes it impossible for users to contribute.

**Comment by beetleskin** [comment]
For starters, you can add your own frontend widget within a custom.js ([ref1](https://github.com/ternaris/marv/blob/7f88dc91b5f4117d637c76c5969367c7bb729a96/docs/widgets.rst#L100), [ref2](https://github.com/ternaris/marv/blob/7f88dc91b5f4117d637c76c5969367c7bb729a96/docs/config/custom.js))

**Comment by chaoflow** [comment]
In order to achieve a small Javascript footprint and high performance on modern browsers, the MARV Robotics web frontend we are providing does not rely on external libraries.

Our aim is to provide a high quality user experience. While we are adding new functionality this still means that the web frontend and its tooling are rapidly changing.

While we intend to fully Open Source these components as well, it has become clear to us that we currently do not have the resources to provide support for this. To be clear about this and not to bloat the repository with generated code, we removed the frontend bundle from the repository. Instead it is [published on PyPI](https://pypi.org/project/marv-ludwig/) and will be [pulled-in](https://github.com/ternaris/marv-robotics/blob/08a892d135245c350acbe7f25bf0c2164d9484d0/code/marv-robotics/setup.py#L20) during installation.

Instead of supporting arbitrary changes to the frontend, we support its customization through well-defined means: [Filters](https://ternaris.com/marv-robotics/docs/config.html#filters), [listing summary](https://ternaris.com/marv-robotics/docs/config.html#listing-summary), [listing columns](https://ternaris.com/marv-robotics/docs/config.html#listing-columns), [detail summary](https://ternaris.com/marv-robotics/docs/config.html#detail-summary-widgets) and [detail sections](https://ternaris.com/marv-robotics/docs/config.html#detail-sections) are all driven by configuration using widgets we provide and widgets [you add yourself](https://ternaris.com/marv-robotics/docs/widgets.html#custom).

[Please let us know](https://github.com/ternaris/marv-robotics/issues/new) if you miss anything.
